version: "3.8"

services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - DB_NAMESPACE=auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
  auth:
    image: supabase/gotrue:v2.142.0
    env_file: 
      - auth.env
    ports:
      - 9999:9999
    environment:
      - GOTRUE_JWT_SECRET=${LETSPLAY_JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data: